/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package memdb.autogen;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ScanContinuation implements org.apache.thrift.TBase<ScanContinuation, ScanContinuation._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ScanContinuation");

  private static final org.apache.thrift.protocol.TField LAST_RECORD_FIELD_DESC = new org.apache.thrift.protocol.TField("lastRecord", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ScanContinuationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ScanContinuationTupleSchemeFactory());
  }

  public QueryIndexRecord lastRecord; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LAST_RECORD((short)1, "lastRecord");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LAST_RECORD
          return LAST_RECORD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.LAST_RECORD};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LAST_RECORD, new org.apache.thrift.meta_data.FieldMetaData("lastRecord", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, QueryIndexRecord.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ScanContinuation.class, metaDataMap);
  }

  public ScanContinuation() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ScanContinuation(ScanContinuation other) {
    if (other.isSetLastRecord()) {
      this.lastRecord = new QueryIndexRecord(other.lastRecord);
    }
  }

  public ScanContinuation deepCopy() {
    return new ScanContinuation(this);
  }

  @Override
  public void clear() {
    this.lastRecord = null;
  }

  public QueryIndexRecord getLastRecord() {
    return this.lastRecord;
  }

  public ScanContinuation setLastRecord(QueryIndexRecord lastRecord) {
    this.lastRecord = lastRecord;
    return this;
  }

  public void unsetLastRecord() {
    this.lastRecord = null;
  }

  /** Returns true if field lastRecord is set (has been assigned a value) and false otherwise */
  public boolean isSetLastRecord() {
    return this.lastRecord != null;
  }

  public void setLastRecordIsSet(boolean value) {
    if (!value) {
      this.lastRecord = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LAST_RECORD:
      if (value == null) {
        unsetLastRecord();
      } else {
        setLastRecord((QueryIndexRecord)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LAST_RECORD:
      return getLastRecord();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LAST_RECORD:
      return isSetLastRecord();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ScanContinuation)
      return this.equals((ScanContinuation)that);
    return false;
  }

  public boolean equals(ScanContinuation that) {
    if (that == null)
      return false;

    boolean this_present_lastRecord = true && this.isSetLastRecord();
    boolean that_present_lastRecord = true && that.isSetLastRecord();
    if (this_present_lastRecord || that_present_lastRecord) {
      if (!(this_present_lastRecord && that_present_lastRecord))
        return false;
      if (!this.lastRecord.equals(that.lastRecord))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ScanContinuation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ScanContinuation typedOther = (ScanContinuation)other;

    lastComparison = Boolean.valueOf(isSetLastRecord()).compareTo(typedOther.isSetLastRecord());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastRecord()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastRecord, typedOther.lastRecord);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ScanContinuation(");
    boolean first = true;

    if (isSetLastRecord()) {
      sb.append("lastRecord:");
      if (this.lastRecord == null) {
        sb.append("null");
      } else {
        sb.append(this.lastRecord);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ScanContinuationStandardSchemeFactory implements SchemeFactory {
    public ScanContinuationStandardScheme getScheme() {
      return new ScanContinuationStandardScheme();
    }
  }

  private static class ScanContinuationStandardScheme extends StandardScheme<ScanContinuation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ScanContinuation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LAST_RECORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.lastRecord = new QueryIndexRecord();
              struct.lastRecord.read(iprot);
              struct.setLastRecordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ScanContinuation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.lastRecord != null) {
        if (struct.isSetLastRecord()) {
          oprot.writeFieldBegin(LAST_RECORD_FIELD_DESC);
          struct.lastRecord.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ScanContinuationTupleSchemeFactory implements SchemeFactory {
    public ScanContinuationTupleScheme getScheme() {
      return new ScanContinuationTupleScheme();
    }
  }

  private static class ScanContinuationTupleScheme extends TupleScheme<ScanContinuation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ScanContinuation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLastRecord()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetLastRecord()) {
        struct.lastRecord.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ScanContinuation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.lastRecord = new QueryIndexRecord();
        struct.lastRecord.read(iprot);
        struct.setLastRecordIsSet(true);
      }
    }
  }

}

